import dns  from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);


import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const interFont = Inter({
  
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      
      className={`${interFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}

